### ISSUE TITLE
Duvida sobre padronização de commits

### ISSUE THREAD

**Issue by natan-xav2019** [Fernanda-Kipper/partners-api#1]
Por que você utiliza feat, refactor, fix e alguma boa prática eu gostei muito como posso usar eles nos meus commits? 

Geralmentes eu só tento descrever eles botar uma foto só para te da uma ideia

![image](https://github.com/Fernanda-Kipper/partners-api/assets/55638524/e9e300bd-c00f-41e7-8f88-5921afa3b41e)

quero fazer commits melhores

**Comment by nslucas** [comment]
Olá, assistindo as lives da Kipper eu tbm percebi isso e comecei a utilizar essa convenção, trata-se de commits semânticos, vc pode ler um pouco mais no link: https://www.conventionalcommits.org/en/v1.0.0/
